# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Instrument.create([

	{ name: "Piano", description: "An acoustic, stringed musical instrument. Most modern pianos have a row of 88 black and white keys. Used often in Jazz, Blues, and Classical ensembles.", image: "/partials/single_instruments/images/piano.png", youtube: "https://www.youtube.com/watch?v=MkFyXDmvbb4&list=PLLsp1gm4FxRgRQ-BW6XSv1l9NhFPAhjfn"},
  { name: "Guitar", description: "A fretted musical instrument that usually has six strings. Most common are classical, steel-string, and jazz. Electric are common for Rock and punk bands.", image: "/partials/single_instruments/images/guitar.png", youtube: "https://www.youtube.com/playlist?list=PLiyMO_9U8g1BNzo7ZoXwKg2Pqt5chP6CT"},
  { name: "Drums", description: "The most popular of the percussion group. Used mostly in rock bands, but certainly have a role in jazz and bradway ensembles", image: "/partials/single_instruments/images/drums.png", youtube: "https://www.youtube.com/watch?v=k_gsp5KwM-k&list=PLLphLKeP1R_JkFoF6nFS3o1xaVzBtJVfp"},
  { name: "Double Bass", description: "The double bass is the largest and lowest-pitched bowed string instrument in the modern symphony orchestra", image: "/partials/single_instruments/images/doublebass.png", youtube: "https://www.youtube.com/watch?v=q3Qpwa5Sf5g&list=PLhik5nSbgHPvmg5M1rnSCuatqsWTqnzJ0"},
  { name: "Saxophone", description: "The saxophone is used in classical music, military bands, marching bands, and jazz (such as big bands and jazz combos).", image: "/partials/single_instruments/images/saxophone.png", youtube: "https://www.youtube.com/watch?v=Ce3hlX93uOg&list=PLuF_UlmBJIShtxxA7iGkXrGORc60_pCGY"},
  { name: "Harmonica", description: "The harmonica is a free reed wind instrument used worldwide in many musical genres, notably in blues, American folk music, classical music, jazz, country, and rock and roll.", image: "/partials/single_instruments/images/harmonica.png", youtube: "https://www.youtube.com/watch?v=m8-aK8egg84&list=PLyv42f0OGtPr6RcYeoGMd1t3Ms5ctWjmi"},
  { name: "Trumpet", description: "A trumpet is a blown musical instrument commonly used in classical and jazz ensembles. The trumpet group contains the instruments with the highest register in the brass family", image: "/partials/single_instruments/images/trumpet.png", youtube: "https://www.youtube.com/watch?v=B18W9LQVnH8&list=PLuF_UlmBJISjXW1A4OGtLiDOBFfoO1yWs"},
  { name: "Trombone", description: "The trombone is a musical instrument in the brass family. Like all brass instruments, sound is produced when the player's vibrating lips (embouchure) cause the air column inside the instrument to vibrate", image: "/partials/single_instruments/images/trombone.png", youtube: "https://www.youtube.com/watch?v=B18W9LQVnH8&list=PLuF_UlmBJISjXW1A4OGtLiDOBFfoO1yWs"},
  { name: "French Horn", description: "The French Horn is a brass instrument made of tubing wrapped into a coil with a flared bell, most often used by players in professional orchestras and bands ", image: "/partials/single_instruments/images/frenchhorn.png", youtube: "https://www.youtube.com/watch?v=5xtqzT1xurw&list=PLarPNySq5QcMus5C7c1NwsMxh4HNDhdhz"},
  { name: "Tuba", description: "The Tuba is the largest and lowest-pitched musical instrument in the brass family", image: "/partials/single_instruments/images/tuba.png", youtube: "https://www.youtube.com/watch?v=UaZGDjr2TfE&list=PL9BAC4CD0C05F419A"},
  { name: "Flute", description: "The Flute a flute is an aerophone or reedless wind instrument that produces its sound from the flow of air across an opening", image: "/partials/single_instruments/images/flute.png", youtube: "https://www.youtube.com/watch?v=IvTY5XDQnig&list=PLuF_UlmBJISg7zI_tbbgHgknJDE7xQBxb"},
  { name: "Clarinet", description: "The clarinet is a musical-instrument with a single-reed mouthpiece, a straight cylindrical tube with an almost cylindrical bore, and a flared bell", image: "/partials/single_instruments/images/clarinet.png", youtube: "https://www.youtube.com/watch?v=QV0XFeWUkbk&list=PLuF_UlmBJISjRdT7D9DdsseYuCjGcuDdX"},
  { name: "Oboe", description: "An Oboe is a double reed woodwind instruments. The most common oboe plays in the treble or soprano range. Oboes are usually made of wood, but there are also oboes made of synthetic materials", image: "/partials/single_instruments/images/oboe.png", youtube: "https://www.youtube.com/watch?v=rX7Z25wp6zo&list=PLAfW2vbt05tGHEqzIiiePoZ8_VKTIrhvr"},
  { name: "Bassoon", description: "The bassoon is a woodwind instrument in the double reed family that typically plays music written in the bass and tenor clefs, and occasionally the treble.", image: "/partials/single_instruments/images/bassoon.png", youtube: "https://www.youtube.com/watch?v=hYRjYZts8Iw&list=PLzw7fvYes9dlOGWm_PJXjLGsidyaxNipm"},
  { name: "Violin", description: "The violin is a wooden string instrument in the violin family. It is the smallest and highest-pitched instrument in the family in regular use", image: "/partials/single_instruments/images/violin.png", youtube: "https://www.youtube.com/watch?v=88G0O5unNuQ&list=PL6urkeK7KgD6z9rImgxwiqBYZVwq31zlg"},
  { name: "Viola", description: "The viola is a string instrument that is bowed or played with varying techniques. It is slightly larger than a violin and has a lower and deeper sound.", image: "/partials/single_instruments/images/viola.png", youtube: "https://www.youtube.com/watch?v=MAzIsk5u4Z4&list=PL0ehFrx9a6zUtGcmeE3flEIOITF2aD0fp"},
  { name: "Cello", description: "The cello is a bowed, and sometimes plucked, string instrument with four strings tuned in perfect fifths.", image: "/partials/single_instruments/images/cello.png", youtube: "https://www.youtube.com/watch?v=eySmCWYBlnU&list=PL3429E4B9D961884F"},
  { name: "Timpani", description: "Timpani are musical instruments in the percussion family", image: "/partials/single_instruments/images/timpani.png", youtube: "https://www.youtube.com/watch?v=4kOBzjSqjGI&list=PL3B5Cc1fjeofWweyx4owBkecldeCB_KeZ"},
  { name: "Steel Drums", description: "Steel Drums is a musical instrument originating from Trinidad and Tobago. Steel pan musicians are called pannists.", image: "/partials/single_instruments/images/steeldrums.png", youtube: "https://www.youtube.com/watch?v=ujp1B2SUX4s&list=PL783D2E9B770C45F9"},
  { name: "Xylophone", description: "The xylophone is a musical instrument in the percussion family that consists of wooden bars struck by mallets", image: "/partials/single_instruments/images/xylophone.png", youtube: "https://www.youtube.com/watch?v=vnFOlhCcz3c&list=PLyfQQ2esRB8INM05cEorJUsii_QF-CNH4"},



])
